### ISSUE TITLE
[Enhancement] Add admin option to list command items

### ISSUE THREAD

**Issue by Dimensional** [Eufranio/CommandItems#3]
At the moment there's no argument for the command to let an administrator list the created command items, so they can have a list to use later on. Having this feature included could really help the admins down the road when they forgot the complete list of command items and what they may do.

**Comment by Eufranio** [comment]
Admins can always open the config file.

**Comment by Dimensional** [comment]
Not unless the admin has access to the server, ie ssh into Linux or through MultiCraft, which most admins and mods wouldn't necessarily have. It would fall to only a few trusted people who could in theory bring down an entire server and destroy virtually everything if they either don't know what they're doing or are being malicious.

And if there's a large amount of CommandItems created, that's a big file that has to be looked through, so the only work around for that is to create a spreadsheet for each command and what they do, a task unto itself not so easy if commands are changed regularly with updates to the server.
